/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main_C_C */

#ifndef _Included_Main_C_C
#define _Included_Main_C_C
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main_C_C
 * Method:    change
 * Signature: (II)Ljava/lang/Long;
 */
JNIEXPORT jobject JNICALL Java_Main_C_C_change
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
